/**
 * Reading `stacks/<id>.stack.yaml` into a tree.
 *
 * The format carries containment and nothing else: a `blocks:` list is a
 * sequence, a `lanes:` list is a parallel, a repeat's `body:` is its single
 * child list, and nesting is the graph. There is no `flow:` edge list and no
 * `.layout.json`, because those two are what this format exists to remove —
 * an edge list can disagree with the nodes, and a layout file can disagree
 * with both (D59).
 *
 * Hand-written, on the loader's hand-written YAML subset, with no
 * dependencies (D24). A stack file is edited by people and generated by
 * models, and neither is well served by a parser with surprises in it.
 *
 * @module #kernel/stack/parse
 */
import { parseYaml, YamlError } from '../loader/yaml.js';
import type { YamlValue } from '../loader/yaml.js';
import type { JsonValue } from '../types.js';
import {
  CONTAINER_KINDS, ID_PATTERN, IF_OPERATORS, MAX_DEPTH, MAX_EXPANSION, MAX_FOR_EACH, MAX_REPEAT, MAX_UNTIL, PLANNED_KINDS,
  boundStack, walk,
  type BlockNode, type ForEachNode, type IfNode, type IfPredicate, type IfPredicateTerm, type IfOperator,
  type ParallelNode, type Position, type RepeatNode, type SequenceNode, type UntilNode,
  type Stack, type StackNode,
} from './types.js';

/** A stack that would not parse, said in one sentence with somewhere to look. */
export class StackError extends Error {
  /** Dotted path from the root: `blocks[1].lanes[0]`. Always present. */
  readonly path: string;
  /** 1-based line, or 0 when the node could not be located in the source. */
  readonly line: number;
  constructor(message: string, path: string, line: number) {
    super(line ? `${message} (${path}, line ${line})` : `${message} (${path})`);
    this.name = 'StackError';
    this.path = path;
    this.line = line;
  }
}

/**
 * Where each id sits in the source.
 *
 * The loader's YAML parser returns values, not positions, and giving it
 * positions would change a shape the composition loader depends on for a
 * benefit only this module wants. So the line is recovered with a second,
 * one-pass scan for `id:` — every node in a stack must have an id, so every
 * node that can be named can be located. A node whose id is MISSING is the one
 * case with no line, and there the path is the whole address, which is honest:
 * there is nothing to point at when the thing that identifies it is absent.
 */
function idLines(source: string): Map<string, number> {
  const out = new Map<string, number>();
  const lines = source.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const m = /^\s*(?:-\s+)?id:\s*['"]?([A-Za-z0-9][A-Za-z0-9_-]*)['"]?\s*(?:#.*)?$/.exec(lines[i]!);
    // First occurrence wins: a duplicate id is refused anyway, and the refusal
    // should point at the first one, so the reader sees what was already taken.
    if (m && !out.has(m[1]!)) out.set(m[1]!, i + 1);
  }
  return out;
}

const isMapping = (v: YamlValue): v is Record<string, YamlValue> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

/** What each shape of node may carry. Anything else is a typo, and is said so. */
/**
 * What a stack may declare an output as.
 *
 * The same closed set `BlockDefinition.outputs` uses (t-0093), written again
 * rather than imported: the parser knows nothing about the block registry by
 * design, and a stack is parsed long before anyone asks which plugin provides
 * what. `list` is the one that carries weight here — it is what lets a roster
 * be told from a sentence.
 */
const OUTPUT_TYPES = ['string', 'number', 'boolean', 'list'];

const BLOCK_KEYS = new Set(['id', 'use', 'title', 'config', 'outputs']);
const SEQUENCE_KEYS = new Set(['id', 'kind', 'blocks']);
const PARALLEL_KEYS = new Set(['id', 'kind', 'lanes', 'maxParallel']);
const REPEAT_KEYS = new Set(['id', 'kind', 'count', 'body']);
const IF_KEYS = new Set(['id', 'kind', 'predicate', 'body', 'else']);
const FOREACH_KEYS = new Set(['id', 'kind', 'roster', 'max', 'body']);
const UNTIL_KEYS = new Set(['id', 'kind', 'condition', 'max', 'body']);
const TERM_KEYS = new Set(['source', 'operator', 'literal']);

interface Ctx {
  lines: Map<string, number>;
  /** id -> where it was first seen, so a duplicate can name both. */
  seen: Map<string, { path: string; line: number }>;
  /**
   * block id -> the fields it declared in `outputs`, and what each one holds,
   * so a predicate can be checked against the authored contract and a `For
   * each` roster can be held to a list rather than to a sentence.
   */
  outputs: Map<string, { line: number; fields: Map<string, string> }>;
}

function lineFor(ctx: Ctx, id: string | null): number {
  return id ? ctx.lines.get(id) ?? 0 : 0;
}

function readId(ctx: Ctx, raw: Record<string, YamlValue>, path: string): string {
  const value = raw['id'];
  if (value === undefined || value === null || value === '') {
    throw new StackError('this node has no id; every block and container needs one', path, 0);
  }
  if (typeof value !== 'string') {
    throw new StackError(`an id must be text, and this one is ${typeof value}`, path, 0);
  }
  if (!ID_PATTERN.test(value)) {
    throw new StackError(
      `"${value}" is not a usable id — start with a letter or digit, then letters, digits, "-" or "_"`,
      path, lineFor(ctx, value));
  }
  const previous = ctx.seen.get(value);
  if (previous) {
    throw new StackError(
      `the id "${value}" is used twice: once at ${previous.path} and again here`,
      path, lineFor(ctx, value));
  }
  ctx.seen.set(value, { path, line: lineFor(ctx, value) });
  return value;
}

function rejectUnknownKeys(
  raw: Record<string, YamlValue>, allowed: Set<string>, what: string, path: string, line: number,
): void {
  const extra = Object.keys(raw).filter(k => !allowed.has(k));
  if (extra.length) {
    throw new StackError(
      `a ${what} does not take ${extra.map(k => `"${k}"`).join(', ')}; it takes ${[...allowed].join(', ')}`,
      path, line);
  }
}

/**
 * Which kind of node this mapping is.
 *
 * `kind` is required on a container and absent on a leaf, so there is exactly
 * one way to write each and no shape to guess at. A kind we have not built is
 * refused by NAME with the phase that brings it.
 */
function kindOf(raw: Record<string, YamlValue>, path: string, line: number): 'block' | 'sequence' | 'parallel' | 'repeat' | 'if' | 'foreach' | 'until' {
  const kind = raw['kind'];
  if (kind === undefined || kind === null) {
    if (raw['blocks'] !== undefined || raw['lanes'] !== undefined || raw['body'] !== undefined
      || raw['predicate'] !== undefined || raw['else'] !== undefined) {
      throw new StackError(
        'a container needs "kind: sequence", "kind: parallel", "kind: repeat", "kind: if", "kind: foreach" or "kind: until"; children alone do not say which',
        path, line);
    }
    return 'block';
  }
  if (typeof kind !== 'string') throw new StackError('"kind" must be text', path, line);
  if (kind === 'block') {
    throw new StackError('a block is written without a "kind"; give it a "use" instead', path, line);
  }
  // `for-each` is how the plan and the editor spell it; one kind, either
  // spelling, normalised here so nothing downstream has to know about both.
  if (kind === 'for-each') return 'foreach';
  if (kind === 'sequence' || kind === 'parallel' || kind === 'repeat' || kind === 'if'
    || kind === 'foreach' || kind === 'until') return kind;
  const planned = PLANNED_KINDS[kind.toLowerCase()];
  if (planned) {
    throw new StackError(
      `"${planned}" is not built yet — it arrives with the rest of bounded control flow in Phase 3 (t-0038). This phase has ${CONTAINER_KINDS.join(' and ')}`,
      path, line);
  }
  throw new StackError(
    `"${kind}" is not a container; this phase has ${CONTAINER_KINDS.join(' and ')}`, path, line);
}

function readChildren(
  ctx: Ctx, raw: Record<string, YamlValue>, key: 'blocks' | 'lanes' | 'body',
  path: string, line: number, depth: number,
): StackNode[] {
  const what = key === 'lanes' ? 'parallel' : key === 'body' ? 'repeat' : 'sequence';
  const value = raw[key];
  if (value === undefined || value === null) {
    throw new StackError(`a ${what} needs "${key}"`, path, line);
  }
  if (!Array.isArray(value)) {
    throw new StackError(`"${key}" must be a list`, path, line);
  }
  if (!value.length) {
    throw new StackError(
      `this container has no ${key}; a container with nothing in it cannot run`, path, line);
  }
  return value.map((child, i) => readNode(ctx, child, `${path}.${key}[${i}]`, depth + 1));
}

/**
 * The roster: an upstream block's declared LIST field, and nothing else.
 *
 * Held to the same contract a predicate source is, plus one more — the field
 * has to be a list. A `type: string` field naming itself as a roster is the
 * "iterate over whatever the last block said" that D56 forbids, and it is
 * refused here rather than split on newlines at run time.
 */
function readRoster(ctx: Ctx, raw: Record<string, YamlValue>, path: string, line: number): string {
  const roster = raw['roster'];
  if (typeof roster !== 'string' || !roster) {
    throw new StackError(
      'a for-each needs "roster", naming a declared list field on an upstream block, like "plan.tasks"',
      path, line);
  }
  const parts = roster.split('.');
  if (parts.length !== 2 || !parts[0] || !parts[1]) {
    throw new StackError(
      `a for-each "roster" is exactly "<block-id>.<field>", and this one says ${JSON.stringify(roster)}`,
      path, line);
  }
  const [block, field] = parts as [string, string];
  const declared = ctx.outputs.get(block);
  if (!declared) {
    const lists = [...ctx.outputs.entries()]
      .flatMap(([id, o]) => [...o.fields].filter(([, t]) => t === 'list').map(([f]) => `${id}.${f}`))
      .sort();
    throw new StackError(
      `the roster names "${roster}", but "${block}" declares no output; upstream list outputs: ${lists.join(', ') || 'none'}`,
      path, line);
  }
  const type = declared.fields.get(field);
  if (type === undefined) {
    throw new StackError(
      `the roster names field "${field}" on block "${block}", which does not declare it; "${block}" declares ${[...declared.fields.keys()].sort().join(', ') || 'no fields'}`,
      path, line);
  }
  if (type !== 'list') {
    throw new StackError(
      `the roster names "${roster}", which "${block}" declares as ${type}. A roster has to be a list — a for-each iterates a declared list, never text split into pieces`,
      path, line);
  }
  return roster;
}

/** The authored bound on how many passes an until gives its body. */
function readUntilMax(raw: Record<string, YamlValue>, path: string, line: number): number {
  const value = raw['max'];
  if (value === undefined || value === null) {
    throw new StackError(
      'an until needs "max", the most passes its body gets before the run gives up — an until without one is the unbounded container this format exists to make impossible',
      path, line);
  }
  if (typeof value !== 'number' || !Number.isInteger(value) || value < 1) {
    throw new StackError('an until "max" must be a whole number of at least 1', path, line);
  }
  return value;
}

/** The authored bound on how many roster elements the body runs for. */
function readForEachMax(raw: Record<string, YamlValue>, path: string, line: number): number {
  const value = raw['max'];
  if (value === undefined || value === null) {
    throw new StackError(
      'a for-each needs "max", the most roster elements its body may run for — the roster itself is not known until the block above has run, so this is the only bound a run can be checked against before it starts',
      path, line);
  }
  if (typeof value !== 'number' || !Number.isInteger(value) || value < 1) {
    throw new StackError('a for-each "max" must be a whole number of at least 1', path, line);
  }
  return value;
}

function readRepeatCount(raw: Record<string, YamlValue>, path: string, line: number): number {
  const value = raw['count'];
  if (value === undefined || value === null) {
    throw new StackError('a repeat needs "count", the number of times to run its body', path, line);
  }
  if (typeof value !== 'number' || !Number.isInteger(value) || value < 1) {
    throw new StackError('a repeat "count" must be a whole number of at least 1', path, line);
  }
  return value;
}

function readTerm(raw: YamlValue, path: string, line: number): IfPredicateTerm {
  if (!isMapping(raw)) {
    throw new StackError(
      'a predicate comparison is a mapping of "source", "operator" and, where the operator compares, "literal"',
      path, line);
  }
  rejectUnknownKeys(raw, TERM_KEYS, 'predicate comparison', path, line);
  const source = raw['source'];
  const dot = typeof source === 'string' ? source.split('.') : [];
  if (typeof source !== 'string' || !source || dot.length !== 2 || !dot[0] || !dot[1]) {
    throw new StackError(
      'a predicate "source" is exactly "<block-id>.<field>", naming a field that block declared',
      path, line);
  }
  const op = raw['operator'];
  if (typeof op !== 'string' || !(IF_OPERATORS as readonly string[]).includes(op)) {
    throw new StackError(
      `"${typeof op === 'string' ? op : ''}" is not a predicate operator; operators are ${IF_OPERATORS.join(', ')}`,
      path, line);
  }
  const operator = op as IfOperator;
  const literal = raw['literal'] as JsonValue | undefined;
  const empty = operator === 'is empty' || operator === 'is not empty';
  if (empty) {
    if (literal !== undefined) throw new StackError(`operator "${operator}" takes no literal`, path, line);
    return { source, operator };
  }
  if (literal === undefined) {
    throw new StackError(`operator "${operator}" needs a literal to compare against`, path, line);
  }
  const t = typeof literal;
  if (t !== 'string' && t !== 'number' && t !== 'boolean') {
    throw new StackError('a predicate literal is text, a number, or a boolean', path, line);
  }
  return { source, operator, literal };
}

function readPredicate(raw: YamlValue, path: string, line: number): IfPredicate {
  if (isMapping(raw) && (raw['allOf'] !== undefined || raw['anyOf'] !== undefined)) {
    const extra = Object.keys(raw).filter(k => k !== 'allOf' && k !== 'anyOf');
    if (extra.length) {
      throw new StackError(
        `a combined predicate takes one of "allOf" or "anyOf", and this also has ${extra.map(k => `"${k}"`).join(', ')}`,
        path, line);
    }
    if (raw['allOf'] !== undefined && raw['anyOf'] !== undefined) {
      throw new StackError('a predicate is either "allOf" or "anyOf", not both', path, line);
    }
    const key = raw['allOf'] !== undefined ? 'allOf' : 'anyOf';
    const list = raw[key];
    if (!Array.isArray(list) || !list.length) {
      throw new StackError(`"${key}" must be a list with at least one comparison`, path, line);
    }
    const terms = list.map((entry, i) => readTerm(entry, `${path}.${key}[${i}]`, line));
    return key === 'allOf' ? { allOf: terms } : { anyOf: terms };
  }
  return readTerm(raw, path, line);
}

function readIfBranch(
  ctx: Ctx, raw: Record<string, YamlValue>, key: 'body' | 'else',
  path: string, line: number, depth: number,
): StackNode[] | null {
  const value = raw[key];
  if (value === undefined || value === null) return null;
  if (!Array.isArray(value)) throw new StackError(`an if "${key}" must be a list`, path, line);
  if (!value.length) {
    throw new StackError(`an if "${key}" cannot be an empty list; leave "${key}" out instead`, path, line);
  }
  return value.map((child, i) => readNode(ctx, child, `${path}.${key}[${i}]`, depth + 1));
}

function readOutputs(ctx: Ctx, raw: Record<string, YamlValue>, id: string, path: string, line: number): void {
  const value = raw['outputs'];
  if (value === undefined || value === null) return;
  if (!Array.isArray(value)) {
    throw new StackError('a block "outputs" is a list, each entry a mapping with a "name"', path, line);
  }
  const fields = new Map<string, string>();
  value.forEach((entry, i) => {
    const entryPath = `${path}.outputs[${i}]`;
    if (!isMapping(entry)) {
      throw new StackError('each output is a mapping with a "name" (and a "type")', entryPath, line);
    }
    const name = entry['name'];
    if (typeof name !== 'string' || !name) {
      throw new StackError('each output needs a "name", the field a predicate or roster names', entryPath, line);
    }
    const type = entry['type'] ?? 'string';
    if (typeof type !== 'string' || !OUTPUT_TYPES.includes(type)) {
      throw new StackError(
        `an output "type" is one of ${OUTPUT_TYPES.join(', ')}, and this one says ${JSON.stringify(type)}`,
        entryPath, line);
    }
    fields.set(name, type);
  });
  ctx.outputs.set(id, { line, fields });
}

function checkPredicate(ctx: Ctx, predicate: IfPredicate, path: string, line: number): void {
  for (const term of predicateTerms(predicate)) {
    const dot = term.source.indexOf('.');
    const block = term.source.slice(0, dot);
    const field = term.source.slice(dot + 1);
    const declared = ctx.outputs.get(block);
    if (!declared) {
      const known = [...ctx.outputs.entries()].sort((a, b) => a[0].localeCompare(b[0]));
      const wantedBy = known.map(([id, o]) => `${id} (${[...o.fields.keys()].sort().join(', ')})`).join('; ');
      throw new StackError(
        `the predicate names "${term.source}", but "${block}" declares no output; upstream blocks that do declare outputs: ${wantedBy || 'none'}`,
        path, line);
    }
    if (!declared.fields.has(field)) {
      throw new StackError(
        `the predicate names field "${field}" on block "${block}", which does not declare it; "${block}" declares ${[...declared.fields.keys()].sort().join(', ') || 'no fields'}`,
        path, line);
    }
  }
}

function predicateTerms(p: IfPredicate): IfPredicateTerm[] {
  if ('source' in p) return [p];
  if ('allOf' in p) return p.allOf;
  return p.anyOf;
}

function readNode(ctx: Ctx, raw: YamlValue, path: string, depth: number): StackNode {
  if (!isMapping(raw)) {
    throw new StackError(
      `expected a block or a container here, and found ${Array.isArray(raw) ? 'a list' : typeof raw}`,
      path, 0);
  }
  const id = readId(ctx, raw, path);
  const line = lineFor(ctx, id);
  const position: Position = { line, path };
  const kind = kindOf(raw, path, line);

  if (kind === 'block') {
    rejectUnknownKeys(raw, BLOCK_KEYS, 'block', path, line);
    const use = raw['use'];
    if (typeof use !== 'string' || !use) {
      throw new StackError(
        'a block needs "use", naming the block type a plugin contributed', path, line);
    }
    const config = raw['config'];
    if (config !== undefined && config !== null && !isMapping(config)) {
      throw new StackError('"config" must be a mapping', path, line);
    }
    const title = raw['title'];
    if (title !== undefined && title !== null && typeof title !== 'string') {
      throw new StackError('"title" must be text', path, line);
    }
    readOutputs(ctx, raw, id, path, line);
    return {
      kind: 'block', id, use,
      title: typeof title === 'string' ? title : null,
      config: (config ?? {}) as Record<string, JsonValue>,
      position,
    } satisfies BlockNode;
  }

  if (depth >= MAX_DEPTH) {
    throw new StackError(
      `containers nest at most ${MAX_DEPTH} deep, root included, and this one is deeper`, path, line);
  }

  if (kind === 'sequence') {
    rejectUnknownKeys(raw, SEQUENCE_KEYS, 'sequence', path, line);
    return {
      kind: 'sequence', id,
      children: readChildren(ctx, raw, 'blocks', path, line, depth),
      position,
    } satisfies SequenceNode;
  }

  if (kind === 'parallel') {
    rejectUnknownKeys(raw, PARALLEL_KEYS, 'parallel', path, line);
    const bound = raw['maxParallel'];
    if (bound !== undefined && bound !== null
      && (typeof bound !== 'number' || !Number.isInteger(bound) || bound < 1)) {
      throw new StackError('"maxParallel" must be a whole number of at least 1', path, line);
    }
    return {
      kind: 'parallel', id,
      maxParallel: typeof bound === 'number' ? bound : null,
      children: readChildren(ctx, raw, 'lanes', path, line, depth),
      position,
    } satisfies ParallelNode;
  }

  if (kind === 'if') {
    rejectUnknownKeys(raw, IF_KEYS, 'if', path, line);
    const predicate = readPredicate(raw['predicate'], `${path}.predicate`, line);
    checkPredicate(ctx, predicate, `${path}.predicate`, line);
    const body = readIfBranch(ctx, raw, 'body', path, line, depth);
    if (!body) throw new StackError('an if needs "body", the branch it runs when the predicate holds', path, line);
    const other = readIfBranch(ctx, raw, 'else', path, line, depth);
    return {
      kind: 'if', id, predicate,
      children: body,
      else: other,
      position,
    } satisfies IfNode;
  }

  if (kind === 'until') {
    rejectUnknownKeys(raw, UNTIL_KEYS, 'until', path, line);
    // The body is read FIRST, so its blocks have declared their outputs by the
    // time the condition is checked. An until normally asks about its own
    // body's verdict — that is the whole shape of "go round again" — and a
    // condition checked before the body was read could only ever name
    // something outside it.
    const children = readChildren(ctx, raw, 'body', path, line, depth);
    const condition = readPredicate(raw['condition'], `${path}.condition`, line);
    checkPredicate(ctx, condition, `${path}.condition`, line);
    return {
      kind: 'until', id, condition,
      max: readUntilMax(raw, path, line),
      children,
      position,
    } satisfies UntilNode;
  }

  if (kind === 'foreach') {
    rejectUnknownKeys(raw, FOREACH_KEYS, 'for-each', path, line);
    const roster = readRoster(ctx, raw, path, line);
    return {
      kind: 'foreach', id, roster,
      max: readForEachMax(raw, path, line),
      children: readChildren(ctx, raw, 'body', path, line, depth),
      position,
    } satisfies ForEachNode;
  }

  rejectUnknownKeys(raw, REPEAT_KEYS, 'repeat', path, line);
  return {
    kind: 'repeat', id,
    count: readRepeatCount(raw, path, line),
    children: readChildren(ctx, raw, 'body', path, line, depth),
    position,
  } satisfies RepeatNode;
}

/**
 * Parse a stack file.
 *
 * @param source — the file's text.
 * @param fallbackId — the id to use when the document does not name one, normally the filename.
 * @returns the stack, containment resolved.
 * @throws {StackError} for anything that would not run, naming a path and, where there is one, a line.
 * @throws {YamlError} for anything outside the YAML subset.
 */
export function parseStack(source: string, fallbackId = ''): Stack {
  // A byte-order mark is not content. Windows editors add one by default, so a
  // hand-written stack file routinely arrives with an invisible character in
  // front of `version:` — and the refusal for that read "unexpected content
  // after the document (line 2)", which points at the wrong line for a problem
  // nobody can see. It is a fact about the file, so it is dropped here rather
  // than described.
  const doc = parseYaml(source.charCodeAt(0) === 0xFEFF ? source.slice(1) : source);
  if (!isMapping(doc)) {
    throw new StackError('a stack file is a mapping with a "blocks" list in it', 'stack', 0);
  }

  const version = doc['version'];
  if (version !== 2) {
    throw new StackError(
      version === 1
        ? 'this is a version 1 flow, not a stack; it is read through the migration path'
        : `a stack is "version: 2", and this says ${JSON.stringify(version ?? null)}`,
      'stack.version', 0);
  }

  const ctx: Ctx = { lines: idLines(source), seen: new Map(), outputs: new Map() };
  const id = typeof doc['id'] === 'string' && doc['id'] ? doc['id'] : fallbackId;
  if (!id) throw new StackError('a stack needs an "id", or a filename to take one from', 'stack.id', 0);

  const blocks = doc['blocks'];
  if (!Array.isArray(blocks) || !blocks.length) {
    throw new StackError('a stack needs a "blocks" list with something in it', 'stack.blocks', 0);
  }

  ctx.seen.set(id, { path: 'stack', line: 0 });
  const root: SequenceNode = {
    kind: 'sequence',
    id,
    children: blocks.map((child, i) => readNode(ctx, child, `blocks[${i}]`, 1)),
    position: { line: 0, path: 'stack' },
  };

  const bounds = boundStack(root);
  if (bounds.expansion > MAX_EXPANSION) {
    throw new StackError(
      `this stack expands to ${bounds.expansion} blocks in the worst case, which is more than the cap of ${MAX_EXPANSION}`,
      'stack', 0);
  }

  for (const node of walk(root)) {
    if (node.kind === 'repeat' && node.count > MAX_REPEAT) {
      throw new StackError(
        `a repeat runs its body at most ${MAX_REPEAT} times, and this one says ${node.count}`,
        node.position.path, node.position.line);
    }
    if (node.kind === 'until' && node.max > MAX_UNTIL) {
      throw new StackError(
        `an until gives its body at most ${MAX_UNTIL} passes, and this one says ${node.max}`,
        node.position.path, node.position.line);
    }
    if (node.kind === 'foreach' && node.max > MAX_FOR_EACH) {
      throw new StackError(
        `a for-each runs its body for at most ${MAX_FOR_EACH} roster elements, and this one says ${node.max}`,
        node.position.path, node.position.line);
    }
  }

  const name = doc['name'];
  const description = doc['description'];
  return {
    version: 2,
    id,
    name: typeof name === 'string' && name ? name : id,
    description: typeof description === 'string' ? description.trim() : '',
    root,
  };
}