/**
 * Reading `stacks/<id>.stack.yaml` into a tree.
 *
 * The format carries containment and nothing else: a `blocks:` list is a
 * sequence, a `lanes:` list is a parallel, a repeat's `body:` is its single
 * child list, and nesting is the graph. There is no `flow:` edge list and no
 * `.layout.json`, because those two are what this format exists to remove —
 * an edge list can disagree with the nodes, and a layout file can disagree
 * with both (D59).
 *
 * Hand-written, on the loader's hand-written YAML subset, with no
 * dependencies (D24). A stack file is edited by people and generated by
 * models, and neither is well served by a parser with surprises in it.
 *
 * @module #kernel/stack/parse
 */
import { parseYaml, YamlError } from '../loader/yaml.js';
import type { YamlValue } from '../loader/yaml.js';
import type { JsonValue } from '../types.js';
import {
  CONTAINER_KINDS, ID_PATTERN, MAX_DEPTH, MAX_EXPANSION, MAX_REPEAT, PLANNED_KINDS,
  boundStack,
  type BlockNode, type ParallelNode, type Position, type RepeatNode, type SequenceNode,
  type Stack, type StackNode,
} from './types.js';

/** A stack that would not parse, said in one sentence with somewhere to look. */
export class StackError extends Error {
  /** Dotted path from the root: `blocks[1].lanes[0]`. Always present. */
  readonly path: string;
  /** 1-based line, or 0 when the node could not be located in the source. */
  readonly line: number;
  constructor(message: string, path: string, line: number) {
    super(line ? `${message} (${path}, line ${line})` : `${message} (${path})`);
    this.name = 'StackError';
    this.path = path;
    this.line = line;
  }
}

/**
 * Where each id sits in the source.
 *
 * The loader's YAML parser returns values, not positions, and giving it
 * positions would change a shape the composition loader depends on for a
 * benefit only this module wants. So the line is recovered with a second,
 * one-pass scan for `id:` — every node in a stack must have an id, so every
 * node that can be named can be located. A node whose id is MISSING is the one
 * case with no line, and there the path is the whole address, which is honest:
 * there is nothing to point at when the thing that identifies it is absent.
 */
function idLines(source: string): Map<string, number> {
  const out = new Map<string, number>();
  const lines = source.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const m = /^\s*(?:-\s+)?id:\s*['"]?([A-Za-z0-9][A-Za-z0-9_-]*)['"]?\s*(?:#.*)?$/.exec(lines[i]!);
    // First occurrence wins: a duplicate id is refused anyway, and the refusal
    // should point at the first one, so the reader sees what was already taken.
    if (m && !out.has(m[1]!)) out.set(m[1]!, i + 1);
  }
  return out;
}

const isMapping = (v: YamlValue): v is Record<string, YamlValue> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

/** What each shape of node may carry. Anything else is a typo, and is said so. */
const BLOCK_KEYS = new Set(['id', 'use', 'title', 'config']);
const SEQUENCE_KEYS = new Set(['id', 'kind', 'blocks']);
const PARALLEL_KEYS = new Set(['id', 'kind', 'lanes', 'maxParallel']);
const REPEAT_KEYS = new Set(['id', 'kind', 'count', 'body']);

interface Ctx {
  lines: Map<string, number>;
  /** id -> where it was first seen, so a duplicate can name both. */
  seen: Map<string, { path: string; line: number }>;
}

function lineFor(ctx: Ctx, id: string | null): number {
  return id ? ctx.lines.get(id) ?? 0 : 0;
}

function readId(ctx: Ctx, raw: Record<string, YamlValue>, path: string): string {
  const value = raw['id'];
  if (value === undefined || value === null || value === '') {
    throw new StackError('this node has no id; every block and container needs one', path, 0);
  }
  if (typeof value !== 'string') {
    throw new StackError(`an id must be text, and this one is ${typeof value}`, path, 0);
  }
  if (!ID_PATTERN.test(value)) {
    throw new StackError(
      `"${value}" is not a usable id — start with a letter or digit, then letters, digits, "-" or "_"`,
      path, lineFor(ctx, value));
  }
  const previous = ctx.seen.get(value);
  if (previous) {
    throw new StackError(
      `the id "${value}" is used twice: once at ${previous.path} and again here`,
      path, lineFor(ctx, value));
  }
  ctx.seen.set(value, { path, line: lineFor(ctx, value) });
  return value;
}

function rejectUnknownKeys(
  raw: Record<string, YamlValue>, allowed: Set<string>, what: string, path: string, line: number,
): void {
  const extra = Object.keys(raw).filter(k => !allowed.has(k));
  if (extra.length) {
    throw new StackError(
      `a ${what} does not take ${extra.map(k => `"${k}"`).join(', ')}; it takes ${[...allowed].join(', ')}`,
      path, line);
  }
}

/**
 * Which kind of node this mapping is.
 *
 * `kind` is required on a container and absent on a leaf, so there is exactly
 * one way to write each and no shape to guess at. A kind we have not built is
 * refused by NAME with the phase that brings it — someone reaching for
 * `For each` should learn where it is from the error, not from the plan.
 */
function kindOf(raw: Record<string, YamlValue>, path: string, line: number): 'block' | 'sequence' | 'parallel' | 'repeat' {
  const kind = raw['kind'];
  if (kind === undefined || kind === null) {
    if (raw['blocks'] !== undefined || raw['lanes'] !== undefined || raw['body'] !== undefined) {
      throw new StackError(
        'a container needs "kind: sequence" or "kind: parallel"; children alone do not say which', path, line);
    }
    return 'block';
  }
  if (typeof kind !== 'string') throw new StackError('"kind" must be text', path, line);
  if (kind === 'block') {
    throw new StackError('a block is written without a "kind"; give it a "use" instead', path, line);
  }
  if (kind === 'sequence' || kind === 'parallel' || kind === 'repeat') return kind;
  const planned = PLANNED_KINDS[kind.toLowerCase()];
  if (planned) {
    throw new StackError(
      `"${planned}" is not built yet — it arrives with the rest of bounded control flow in Phase 3 (t-0038). This phase has ${CONTAINER_KINDS.join(' and ')}`,
      path, line);
  }
  throw new StackError(
    `"${kind}" is not a container; this phase has ${CONTAINER_KINDS.join(' and ')}`, path, line);
}

function readChildren(
  ctx: Ctx, raw: Record<string, YamlValue>, key: 'blocks' | 'lanes' | 'body',
  path: string, line: number, depth: number,
): StackNode[] {
  const what = key === 'lanes' ? 'parallel' : key === 'body' ? 'repeat' : 'sequence';
  const value = raw[key];
  if (value === undefined || value === null) {
    throw new StackError(`a ${what} needs "${key}"`, path, line);
  }
  if (!Array.isArray(value)) {
    throw new StackError(`"${key}" must be a list`, path, line);
  }
  if (!value.length) {
    // An empty container is not a stack with a hole in it — it is a container
    // that runs nothing, which is never what anyone meant to write.
    throw new StackError(
      `this container has no ${key}; a container with nothing in it cannot run`, path, line);
  }
  return value.map((child, i) => readNode(ctx, child, `${path}.${key}[${i}]`, depth + 1));
}

function readRepeatCount(raw: Record<string, YamlValue>, path: string, line: number): number {
  const value = raw['count'];
  if (value === undefined || value === null) {
    throw new StackError('a repeat needs "count", the number of times to run its body', path, line);
  }
  if (typeof value !== 'number' || !Number.isInteger(value) || value < 1) {
    throw new StackError('"count" must be a whole number of at least 1', path, line);
  }
  if (value > MAX_REPEAT) {
    throw new StackError(
      `a repeat runs its body at most ${MAX_REPEAT} times, and this one says ${value}`,
      path, line);
  }
  return value;
}

function readNode(ctx: Ctx, raw: YamlValue, path: string, depth: number): StackNode {
  if (!isMapping(raw)) {
    throw new StackError(
      `expected a block or a container here, and found ${Array.isArray(raw) ? 'a list' : typeof raw}`,
      path, 0);
  }
  const id = readId(ctx, raw, path);
  const line = lineFor(ctx, id);
  const position: Position = { line, path };
  const kind = kindOf(raw, path, line);

  if (kind === 'block') {
    rejectUnknownKeys(raw, BLOCK_KEYS, 'block', path, line);
    const use = raw['use'];
    if (typeof use !== 'string' || !use) {
      throw new StackError(
        'a block needs "use", naming the block type a plugin contributed', path, line);
    }
    const config = raw['config'];
    if (config !== undefined && config !== null && !isMapping(config)) {
      throw new StackError('"config" must be a mapping', path, line);
    }
    const title = raw['title'];
    if (title !== undefined && title !== null && typeof title !== 'string') {
      throw new StackError('"title" must be text', path, line);
    }
    return {
      kind: 'block', id, use,
      title: typeof title === 'string' ? title : null,
      // Not interpreted: what a block's settings mean is the block's business,
      // and a parser that validated them would be a parser that has to be
      // taught every plugin ever installed.
      config: (config ?? {}) as Record<string, JsonValue>,
      position,
    } satisfies BlockNode;
  }

  if (depth >= MAX_DEPTH) {
    throw new StackError(
      `containers nest at most ${MAX_DEPTH} deep, root included, and this one is deeper`, path, line);
  }

  if (kind === 'sequence') {
    rejectUnknownKeys(raw, SEQUENCE_KEYS, 'sequence', path, line);
    return {
      kind: 'sequence', id,
      children: readChildren(ctx, raw, 'blocks', path, line, depth),
      position,
    } satisfies SequenceNode;
  }

  if (kind === 'parallel') {
    rejectUnknownKeys(raw, PARALLEL_KEYS, 'parallel', path, line);
    const bound = raw['maxParallel'];
    if (bound !== undefined && bound !== null
      && (typeof bound !== 'number' || !Number.isInteger(bound) || bound < 1)) {
      throw new StackError('"maxParallel" must be a whole number of at least 1', path, line);
    }
    return {
      kind: 'parallel', id,
      maxParallel: typeof bound === 'number' ? bound : null,
      children: readChildren(ctx, raw, 'lanes', path, line, depth),
      position,
    } satisfies ParallelNode;
  }

  rejectUnknownKeys(raw, REPEAT_KEYS, 'repeat', path, line);
  return {
    kind: 'repeat', id,
    count: readRepeatCount(raw, path, line),
    children: readChildren(ctx, raw, 'body', path, line, depth),
    position,
  } satisfies RepeatNode;
}

/**
 * Parse a stack file.
 *
 * @param source — the file's text.
 * @param fallbackId — the id to use when the document does not name one, normally the filename.
 * @returns the stack, containment resolved.
 * @throws {StackError} for anything that would not run, naming a path and, where there is one, a line.
 * @throws {YamlError} for anything outside the YAML subset.
 */
export function parseStack(source: string, fallbackId = ''): Stack {
  const doc = parseYaml(source);
  if (!isMapping(doc)) {
    throw new StackError('a stack file is a mapping with a "blocks" list in it', 'stack', 0);
  }

  const version = doc['version'];
  if (version !== 2) {
    // Version 1 is a FLOW. It is read through the migration path and adopted
    // on first write, exactly as `.llmflow/` -> `.flyt/` works — never here,
    // because a flow has an edge list and this parser has nowhere to put one.
    throw new StackError(
      version === 1
        ? 'this is a version 1 flow, not a stack; it is read through the migration path'
        : `a stack is "version: 2", and this says ${JSON.stringify(version ?? null)}`,
      'stack.version', 0);
  }

  const ctx: Ctx = { lines: idLines(source), seen: new Map() };
  const id = typeof doc['id'] === 'string' && doc['id'] ? doc['id'] : fallbackId;
  if (!id) throw new StackError('a stack needs an "id", or a filename to take one from', 'stack.id', 0);

  const blocks = doc['blocks'];
  if (!Array.isArray(blocks) || !blocks.length) {
    throw new StackError('a stack needs a "blocks" list with something in it', 'stack.blocks', 0);
  }

  // The root is a sequence, always. A stack IS a sequence whatever else it
  // holds, which is why the top level needs no `kind`, and why the editor has
  // one shape to lay out rather than two.
  ctx.seen.set(id, { path: 'stack', line: 0 });
  const root: SequenceNode = {
    kind: 'sequence',
    id,
    children: blocks.map((child, i) => readNode(ctx, child, `blocks[${i}]`, 1)),
    position: { line: 0, path: 'stack' },
  };

  // The second bound (MAX_DEPTH is the first): worst-case expansion over the
  // whole tree. It must be computed and refused before anything runs, so the
  // parser is the last place that sees every tree exactly once.
  const bounds = boundStack(root);
  if (bounds.expansion > MAX_EXPANSION) {
    throw new StackError(
      `this stack expands to ${bounds.expansion} blocks in the worst case, which is more than the cap of ${MAX_EXPANSION}`,
      'stack', 0);
  }

  const name = doc['name'];
  const description = doc['description'];
  return {
    version: 2,
    id,
    name: typeof name === 'string' && name ? name : id,
    description: typeof description === 'string' ? description.trim() : '',
    root,
  };
}
