/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7cd2f4133e3a01838c7687385b060a5e)
interface __BaseEnv_Env {
	RELEASES: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface StagingEnv {
		RELEASES: R2Bucket;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
